### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by justrubbish** [studiomitte/friendlycaptcha-typo3#2]
T3 v12.5.4 & T3 v12.5.32 
trying to install directly through the T3 backend and to upload .zip to the backend - immediately the complete System ist broken and just an Empty html site ist loaded.
After deletion of EXT from PackageStates.php Backend and Frondend ist working properly again...
Are there any known issues?

Thanks a lot

**Comment by justrubbish** [comment]
some more info:

Wed, 11 Oct 2023 23:58:04 +0200 [CRITICAL] request="56c409a04708d" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB: BE): Symfony\Component\DependencyInjection\Exception\InvalidArgumentException, code #0, file /html/typo3/typo3_src-12.4.5/vendor/symfony/dependency-injection/Loader/FileLoader.php, line 230: Expected to find class "StudioMitte\FriendlyCaptcha\Configuration" in file "/html/typo3/typo3conf/ext/friendlycaptcha_official/Classes/Configuration.php" while importing services from resource "../Classes/*", but it was not found! Check the namespace prefix used with the resource. - {"mode":"WEB","application_mode":"BE","exception_class":"Symfony\\Component\\DependencyInjection\\Exception\\InvalidArgumentException","exception_code":0,"file":"/html/typo3/typo3_src-12.4.5/vendor/symfony/dependency-injection/Loader/FileLoader.php","line":230,"message":"Expected to find class \"StudioMitte\\FriendlyCaptcha\\Configuration\" in file \"/html/typo3/typo3conf/ext/friendlycaptcha_official/Classes/Configuration.php\" while importing services from resource \"../Classes/*\", but it was not found! Check the namespace prefix used with the resource.","request_url":"http://p648945.mittwaldserver.info/","exception":null}

**Comment by georgringer** [comment]
Which zip do you use? A zip downloaded from github or ter? Which files are inside tyoo3conf/ext/friendlycaptcha_official?

**Comment by justrubbish** [comment]
zip from TER

directories:
- Build
- Classes
- Configuration
- Documentation
- Resources
- Tests

files:
- LICENSE.txt
- README.md
- composer.json
- ext_emconf.php
- ext_localconf.php

**Comment by georgringer** [comment]
just moved the download from ter to typo3conf/ext/friendlycaptcha_official , installed ext via backend in a 11.5.31 and worked fine. can you test it on a different installation?

**Comment by justrubbish** [comment]
tried to install in a fresh 11.5.32 + bootstrap_pakage 14 + powermail 10 -> works fine
deinstalled friendlycaptcha, deactivated powermail, Updated T3 to 12.4.6, updated to Powermail 11 then tried to reinstall friendlycaptcha from TER -> same problem. Installation process doesn't finish. Browser reload produce just an empty html output...

**Comment by georgringer** [comment]
we are on it to support powermail v11

**Comment by georgringer** [comment]
I just merged a testing branch, please test the main branch!

**Comment by justrubbish** [comment]
captcha is shown, verification seems to work, but after submitting Form error Captcha invalid - try again is shown

- installation was  successful
- configuration in Sites Module as described (Site & Secure key given)
- static page TSconfig & TS-Template included

Error message -> Core: Error handler (FE): PHP Warning: Undefined array key "config" in /html/typo3/typo3conf/ext/powermail/Classes/Domain/Validator/ForeignValidator.php line 43

**Comment by georgringer** [comment]
which version of powermail are you using? `/html/typo3/typo3conf/ext/powermail/Classes/Domain/Validator/ForeignValidator.php line 43` => this is an issue in powermail.

i will retest everything on monday

**Comment by justrubbish** [comment]
tested in version 11.0.1 & 12.0.2

**Comment by georgringer** [comment]
I tested now 12.0.2 and works as well. As you can see in https://github.com/studiomitte/friendlycaptcha-typo3/blob/main/Configuration/TypoScript/Powermail/setup.typoscript#L10-L12, the config is set there as empty array.

I suggest to modify the line of powermail in the following way
```php
$validator = GeneralUtility::makeInstance($validatorConf['class']);
                if (!isset($validatorConf['config'])) {
                    print_r($validatorConf);die;
                }
                $validator->setConfiguration((array)$validatorConf['config']);
```
(so adding the if check) and you will see the ts/class which triggers the error

**Comment by dirnbauer** [comment]
regarding latest powermail 12.0.3 and TYPO3 lts12:

I had to add a dummy typoscript to avoid the error from https://github.com/studiomitte/friendlycaptcha-typo3/issues/2#issuecomment-1859699056

```
 config {
                test-ignore = 1
            }
```

```
[compatVersion("12.4")]
    plugin.tx_powermail.settings.setup.validators {
        981818 {
            class = StudioMitte\FriendlyCaptcha\FieldValidator\PowermailV11Validator
            config {
                test-ignore = 1
            }
        }
    }
[global]
```
