### ISSUE TITLE
Site KEY?

### ISSUE THREAD

**Issue by asche76** [studiomitte/friendlycaptcha-typo3#23]
where do i get the Site KEY from?
when i create a new Secret KEY on friendlycaptcha there is no site key...

![image](https://github.com/studiomitte/friendlycaptcha-typo3/assets/47745128/5ad656eb-c80e-47be-acd4-b418a28fec42)

![image](https://github.com/studiomitte/friendlycaptcha-typo3/assets/47745128/3eb4c1aa-5605-4009-80fd-21c20a192443)

**Comment by LightsOnDeveloper** [comment]
I have got the same problem. Did you have solved it and how?

**Comment by asche76** [comment]
you find the site key in the overview in the customer area on the friendly captcha website -> your APIs or something

**Comment by LightsOnDeveloper** [comment]
Yes, I have an site key in site configuration, but I see in friendly captcha dashboard, that the eu endpoint is not a available option to set

**Comment by asche76** [comment]
eu-endpoint only with payed versions, "starter" is minimum
