### ISSUE TITLE
Installation affects PHP Fatal error

### ISSUE THREAD

**Issue by mpruy** [studiomitte/friendlycaptcha-typo3#3]
The installation of the extension leads to a PHP Fatal Error. The error occurs immediately after installation and subsequent clearing of the cache.

`The Installation PHP message: PHP Fatal error:  Class StudioMitte\\FriendlyCaptcha\\FieldValidator\\PowermailValidator contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (TYPO3\\CMS\\Extbase\\Validation\\Validator\\AbstractValidator::isValid) in /var/www/xxx/htdocs/vendor/studiomitte/friendlycaptcha/Classes/FieldValidator/PowermailValidator.php on line 0`

TYPO3 Version 12.4.6.
PHP Version 8.2.10

**Comment by georgringer** [comment]
cant reproduce, please provide powermail version you are using
